DROP TABLE IF EXISTS equipment;
DROP TABLE IF EXISTS substations;

create table substations (
    id bigint generated by default as identity primary key ,
    voltageclass integer,
    name varchar(255)
    );

create table equipment (
    id bigint generated by default as identity primary key ,
    name varchar(255),
    type varchar(255),
    substation_id bigint,
    FOREIGN KEY (substation_id) REFERENCES substations(id)
    );

INSERT INTO substations (voltageclass, name) VALUES
    (110, 'Mamulino'),
    (110, 'Papulino'),
    (220, 'Slavyanskaya');

INSERT INTO equipment(name, type, substation_id) VALUES
    ('Tr1', 'Transformer', 1),
    ('Tr2', 'Transformer', 1),
    ('Breaker-1', 'Breaker', 1),
    ('Bus-110', 'Bus', 1),
    ('Bus-10', 'Bus', 1),
    ('Bus-110', 'Bus', 2),
    ('Bus-10', 'Bus', 2);
